services:
  dev_container:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      # Mount the repo folder contents into the container so we can use the code.
      - .:/project:cached
    env_file: .env
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
