site_name: flask-api-sqlalchemy
site_description: Flask extension for automatically generating RESTful APIs from SQLAlchemy models
site_url: https://mccarthysean.dev/flask-api-sqlalchemy
repo_name: mccarthysean/flask-api-sqlalchemy
repo_url: https://github.com/mccarthysean/flask-api-sqlalchemy
edit_uri: ""
# google_analytics:
#   - G-Z6DZ02583Q
#   - auto

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/lightbulb-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    repo: fontawesome/brands/github-alt
  logo: img/icon-white.svg
  favicon: img/favicon.png
  language: en

plugins:
  # Material for MkDocs
  search:
  social:

nav:
  - flask-api-sqlalchemy: index.md

markdown_extensions:
  # Python Markdown
  abbr:
  attr_list:
  footnotes:
  md_in_html:
  tables:
  toc:
    permalink: true

  # Python Markdown Extensions
  pymdownx.betterem:
    smart_enable: all
  pymdownx.caret:
  pymdownx.highlight:
    line_spans: __span
  pymdownx.inlinehilite:
  pymdownx.keys:
  pymdownx.mark:
  pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  pymdownx.tilde:

  # pymdownx blocks
  pymdownx.blocks.admonition:
    types:
      - note
      - attention
      - caution
      - danger
      - error
      - tip
      - hint
      - warning
      # Custom types
      - info
  pymdownx.blocks.details:
  pymdownx.blocks.tab:
    alternate_style: True

  # Other extensions
  mdx_include:

extra:
  analytics:
    provider: google
    property: G-DXZ6N63Y4N
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mccarthysean/flask-api-sqlalchemy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mccarthysean
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mccarthysean
    - icon: fontawesome/brands/dev
      link: https://dev.to/mccarthysean
    - icon: fontawesome/brands/medium
      link: https://medium.com/@mccarthysean
    - icon: fontawesome/solid/globe
      link: https://mccarthysean.dev

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

hooks:
  - scripts/mkdocs_hooks.py
